### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Batarian711** [aBARICHELLO/GAMINE#4]
Hi. I am a graphic designer. I volunteer to design a logo for open source projects. I can design it for you to use it in the readme file. What dou you say?

**Comment by abarichello** [comment]
Hey @Batarian711, i would be glad if you did!
I don't have much to return in terms of exposure, but i sure will credit you where i use the provided logos.
Thanks.

**Comment by Batarian711** [comment]
Inspired by the old game console, I designed a minimalist logo. Is there anything you want to add ?

![gamine](https://user-images.githubusercontent.com/41051393/42755996-f02d55ee-8902-11e8-92c5-c48ddb45b253.jpg)

**Comment by abarichello** [comment]
Thanks for the logo @Batarian711!
